version: '3.1'

services:
  frontend:
    build:
      context: ../..
      dockerfile: ./docker/production/Dockerfile
    volumes:
      - "docker/production/data/certbot/conf:/etc/letsencrypt"
      - "docker/production/data/certbot/www:/var/www/certbot"
      - "docker/production/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
      - "443:443"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    depends_on:
      - frontend
    container_name: certbot
    volumes:
      - "./data/certbot/conf:/etc/letsencrypt"
      - "./data/certbot/www:/var/www/certbot"
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
