export { ChangePasswordPage } from './change-password';
export { ChatPage } from './chat';
export { HomePage } from './home';
export { LoginPageView } from './login';
export { ProfilePage } from './profile';
export { SignInPageView } from './sign-up';
export { UpdateProfilePage } from './update-profile';
export { ClientErrorPage } from './404';
export { ServerErrorPage } from './500';
